apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: sports
spec:
  clusterIP: None  # Headless service
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-read-only
  namespace: sports
spec:
  type: NodePort
  selector:
    role: slave
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-write
  namespace: sports
spec:
  type: NodePort
  selector:
    role: master
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 30002
